export const shops=[
 {name:'BIKE24',host:'www.bike24.de',path:(q:string)=>'/suchergebnis?searchTerm='+encodeURIComponent(q)},
 {name:'Bike-Discount',host:'www.bike-discount.de',path:(q:string)=>'/de/search?search='+encodeURIComponent(q)},
 {name:'bike-components',host:'www.bike-components.de',path:(q:string)=>'/de/s/?keywords='+encodeURIComponent(q)},
 {name:'r2-bike',host:'r2-bike.com',path:(q:string)=>'/?qs='+encodeURIComponent(q)}
];
function decode(s:string){return s.replace(/&quot;/g,'"').replace(/&#039;|&#39;|&apos;/g,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');}
export function jsonData(html:string){const out:any[]=[];for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)){if(/application\/(?:ld\+)?json/.test(m[1]))try{out.push(JSON.parse(m[2]));}catch{}}for(const m of html.matchAll(/data-props=(['"])([\s\S]*?)\1/gi))try{out.push(JSON.parse(decode(m[2])));}catch{}return out;}
function walk(v:any,fn:(x:any)=>void){if(!v||typeof v!=='object')return;fn(v);for(const x of Object.values(v))walk(x,fn);}
function safeLink(link:string,host:string){try{const u=new URL(link,'https://'+host);return u.protocol==='https:'&&u.hostname===host?u.href:null;}catch{return null;}}
async function page(url:string,host:string){const r=await fetch(url,{headers:{'Accept':'text/html,application/json','User-Agent':'Teilefinder/1.0'},signal:AbortSignal.timeout(12000),redirect:'follow'});if(new URL(r.url||url).hostname!==host)throw Error('Weiterleitung außerhalb des Shops.');const html=await r.text();if(!r.ok||/Just a moment\.\.\.|Access Denied|cf-chl-|captcha/i.test(html.slice(0,15000)))throw Error('Automatische Abfrage vom Shop blockiert.');if(html.length>2500000)throw Error('Shop-Antwort zu groß.');return html;}
function price(p:any){const n=Number(p);return p!==undefined&&p!==null&&p!==''&&Number.isFinite(n)&&n>0?Math.round(n*100)/100:null;}
export function bcProducts(html:string){const found=new Map<number,any>();for(const obj of jsonData(html))walk(obj,x=>{if(x.type==='variant'&&x.data?.productName&&x.data?.link&&x.data?.priceRaw!==undefined)found.set(x.productId,x.data);});return [...found.values()];}
export function bcOffers(html:string,host:string,productId:number){const found=new Map<string,any>();for(const obj of jsonData(html))walk(obj,x=>{if(x.type!=='option'||x.productId!==productId||!x.data?.productName)return;const d=x.data,url=safeLink(d.link,host);if(!url)return;found.set(url,{name:d.productName,variant:d.optionName||'',price:price(d.priceRaw),stock:d.availability?.text||'Lagerstatus nicht auslesbar',url});});return [...found.values()];}
function genericOffers(html:string,host:string){const found:any[]=[];for(const obj of jsonData(html))walk(obj,x=>{if(x['@type']!=='Product'||!x.name||!x.offers)return;for(const o of Array.isArray(x.offers)?x.offers:[x.offers]){const url=safeLink(o.url||x.url,host);if(!url)continue;const status=String(o.availability||'').split('/').pop()||'';found.push({name:String(x.name),variant:x.sku?'Artikel '+x.sku:'',price:o.priceCurrency==='EUR'?price(o.price):null,stock:({InStock:'Auf Lager',OutOfStock:'Ausverkauft',PreOrder:'Vorbestellung',BackOrder:'Nachbestellung'} as any)[status]||'Lagerstatus nicht auslesbar',url});}});return found.slice(0,12);}
export async function searchShop(shop:typeof shops[number],q:string){const url='https://'+shop.host+shop.path(q);let offers:any[]=[],message='';try{const html=await page(url,shop.host);if(shop.name==='bike-components'){const tokens=q.toLowerCase().split(/\s+/).filter(Boolean);const products=bcProducts(html).filter(d=>tokens.every(t=>/^\d{8,14}$/.test(t)||String(d.productName).toLowerCase().includes(t)||String(d.productId)===t)).slice(0,4);const detail=await Promise.allSettled(products.map(async d=>{const link=safeLink(d.link,shop.host);if(!link)return [];try{const rows=bcOffers(await page(link,shop.host),shop.host,d.productId);if(rows.length)return rows;}catch{}return [{name:d.productName,variant:'Ausführung im Shop prüfen · ab-Preis',price:price(d.priceRaw),stock:'Lagerstatus nicht auslesbar',url:link}];}));offers=detail.flatMap(d=>d.status==='fulfilled'?d.value:[]);message=products.length?'':'Keine passenden Treffer ausgelesen. Bitte die Suche im Shop prüfen.';}else{offers=genericOffers(html,shop.host);if(!offers.length)message='Preis und Lagerstatus nicht abrufbar. Bitte die Shopsuche öffnen.';}}catch(e){message=e instanceof Error&&e.message.includes('blockiert')?'Automatische Abfrage vom Shop blockiert. Preis und Lagerstatus nicht abrufbar.':'Shop derzeit nicht erreichbar oder Antwort nicht auslesbar.';}return {name:shop.name,url,offers:offers.sort((a,b)=>(a.price??Infinity)-(b.price??Infinity)),message,checkedAt:new Date().toISOString()};}
